# Generated by Django 4.0 on 2023-01-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Список дел", max_length=64)),
                (
                    "is_done",
                    models.BooleanField(default=False, help_text="Выполнено ли дело"),
                ),
            ],
            options={
                "verbose_name_plural": "Дела",
            },
        ),
    ]
