# Generated by Django 4.0 on 2023-01-27 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="timestamp_start",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Время формирования задания",
            ),
            preserve_default=False,
        ),
    ]
