# Generated by Django 4.0 on 2023-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_todo_timestamp_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="timestamp_end",
            field=models.DateTimeField(
                blank=True, help_text="Время выполнения задания", null=True
            ),
        ),
    ]
